### ISSUE TITLE
3 problems with a map on WM staging

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#592] opened 2019-03-26 15:50 UTC
http://128.31.22.103/maps/46646/view 
In this map, which includes a newly created layer (cambridge wetlands) and an older layer (historic wetlands, and a map service (1903 Bromely), there are some issues.
1) Identify on cambridge wetlands waits a long time then comes back with nothing
2) Identify on historic wetlands does not do anything
3) when I save the map with Bromley turned off it comes back when I refresh the map as turned on

**Comment by capooti** [comment] 2019-03-27 15:41
I don't know, it needs some debug and I haven't time for it right now. Will look into this in April.
I noticed that identify from WMS is working well, so the problem is with WFS identify. You can test this by accessing anonymously to the same layer.

**Comment by capooti** [comment] 2019-05-17 21:16
I am closing this as I believe is related to problem with the data and not to a specific bug.

**Closed as completed by capooti** 2019-05-17 21:16 UTC
Labels: migration, paolo-deliv-3
