### ISSUE TITLE
When point layer is created no way to add data

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#593] opened 2019-03-26 19:13 UTC
Here is the layer I created http://128.31.22.103/layers/geonode:test678
THis is on firefox windows
![image](https://user-images.githubusercontent.com/812849/55026754-0e20b480-4fda-11e9-979b-6a1db098fd9d.png)

**Comment by capooti** [comment] 2019-03-27 15:45
I could successfully add a point.
There are not fields created for this layer, so no way to edit attributes.

**Comment by capooti** [comment] 2019-04-29 15:56
I close this. If you think the issue is still there please re-open it.

**Closed as completed by capooti** 2019-04-29 15:56 UTC
Labels: migration, paolo-deliv-3
