### ISSUE TITLE
WM staging - clould not edit style of layer I own

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#583] opened 2018-12-18 20:52 UTC
http://128.31.22.103/layers/geonode:trump_international_ue2

**Comment by capooti** [comment] 2018-12-18 21:04
this is generally caused by the expiration of the OAuth token when your browser session is inactive for a while. Could you try to logout, login again and re-try to edit the style?

**Comment by capooti** [comment] 2019-01-15 23:00
Could you do what I suggested and see if it replicates? thanks

**Comment by capooti** [comment] 2019-01-17 20:48
@bglewis check this discussion: https://github.com/GeoNode/geonode/issues/3563

I have now set ACCESS_TOKEN_EXPIRE_SECONDS to 1 year. If you again are unable to edit data or styles for any layer which you believe you have permissions let me know because in that case this didn't help.

**Comment by capooti** [comment] 2019-01-22 16:31
Unfortunately changing this setting seem not having fixed things.

**Comment by capooti** [comment] 2019-05-17 21:20
Closing this, we have another one open.

**Closed as completed by capooti** 2019-05-17 21:20 UTC
Labels: migration
