### ISSUE TITLE
post_save layer GeoNode signal is causing style editor unpredictable behaviour

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#600] opened 2019-05-02 13:54 UTC
http://128.31.22.46/maps/new?layer=geonode:xiandaizuojiamidu  , style "ben new style"

**Comment by blewis** [comment] 2019-05-10 18:06
Just determined that, for points, once one edits the stroke, any changes to the fill suddenly become activated.  Before editing the stroke it appears that it is not possible to change the color of the style fill.

**Comment by capooti** [comment] 2019-05-10 22:10
For me it is working only second time. For example:
* I edit the size
* I change the color (does not work)
* I change the color (it works)

I believe these kind of problems are generated by the much slower response of GeoNode when changing a symbol (which could be caused by the thumbnail being generated)

**Comment by capooti** [comment] 2019-05-17 20:50
So I think these problems could be caused by the very slow response from GeoNode for each action in the style editor. Basically for each change in the style, a post_save signals is sent from layer. This takes some time itself, furthermore it also re-generates the thumbnail which shouldn't happen.
Reported this here: https://github.com/GeoNode/geonode/issues/4410

**Comment by capooti** [comment] 2019-05-22 20:57
All these problems are generated by layer post_save signal which is activated after every style changes. Now Alessio mitigated it by not having the thumbnail regenerated every time, but it is still very slow.

I am discussing about this issue here: 
https://github.com/GeoNode/geonode/pull/4411#event-2351344915

**Comment by capooti** [comment] 2019-05-23 19:48
This is addressed and I have sent a PR here:
https://github.com/GeoNode/geonode/pull/4430

**Comment by capooti** [comment] 2019-06-06 21:46
This is now fixed both in CAMP and WM staging.

**Closed as completed by capooti** 2019-06-06 21:46 UTC
Labels: Addendum1
