### ISSUE TITLE
Add click through terms of service for account creation and map creation as well as layer creation.

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#123] opened 2016-08-08 21:53 UTC

**Comment by capooti** [comment] 2017-01-27 22:49
We have this now in account and layer creation, but not in map: can we close it or we still need it in map as well @bglewis ?

**Comment by capooti** [comment] 2017-01-27 22:51
Closing as it is a duplicate of #128

**Closed by capooti** 2017-01-27 22:51 UTC
Labels: UI
