### ISSUE TITLE
CAMP staging -layer page does not allow identify

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#603] opened 2019-05-10 18:55 UTC
CAMP staging - user not logged in accessing a layer which has downloads turned off, layer page does not allow identify

**Comment by capooti** [comment] 2019-05-10 21:03
I tried to replicate this without success. For example, here is a layer on which I disabled download for all users:
http://128.31.22.46/maps/new?layer=geonode:tm_world_borders_0_3_1

I can identify both as anonymous and as logged user.
Did you notice this issue on a specific layer?

**Comment by blewis** [comment] 2019-05-10 21:10
Yes meant to send layer http://amap.zju.edu.cn/layers/geonode:piyingzhengchang

**Comment by capooti** [comment] 2019-05-10 21:24
For me this works both on Firefox and Chrome if I am anonymous or logged. Can you replicate the problem?

**Comment by blewis** [comment] 2019-05-10 21:37
This layer http://amap.zju.edu.cn/layers/geonode:piyingzhengchang when not logged in on firefox windows I cannot do identify on layer page

**Comment by capooti** [comment] 2019-05-10 22:21
So we could say that the problem is with Windows Firefox? (for me is working in  Firefox on OSX)
Can you please try to see what happens after restarting Firefox? Could you also check if you see any error in the browser console?

http://recordit.co/wVdn29K6ml

**Comment by capooti** [comment] 2019-05-17 18:35
hey @bglewis did you have the chance to test this again? For me it is working (on osx) in Chrome, Firefox and Safari. Let me know if you still have the issue, otherwise I could close this.

**Comment by capooti** [comment] 2019-05-24 16:13
@bglewis let me know if I can close this.

**Comment by blewis** [comment] 2019-05-24 16:28
Still cannot make Identify command work on any layer page on production CAMP using chrome or firefox.

**Comment by blewis** [comment] 2019-05-24 16:29
But maybe they are not having this problem.  We should check though.

**Comment by capooti** [comment] 2019-05-24 18:06
For me it is working on Chrome, Firefox and Safari. Do you have the identify tool selected? (by default is not - which is something which could be confusing and we can change)

**Comment by blewis** [comment] 2019-05-24 18:36
My fault.  Didn't have identify tool selected.  We can leave as is.

**Closed as completed** 2019-05-24 20:05 UTC
Labels: Addendum1, feedback-needed
